### ISSUE TITLE
Wrong ground-truth images being logged during training

### ISSUE THREAD

**Issue by schmidtdominik** [FLAIROx/jafar#1]
The ground-truth reference logged images during training here

https://github.com/FLAIROx/jafar/blob/6509ffc0d54e25c177adb8c016a472ae4d376a6d/train_tokenizer.py#L160

are actually the dummy inputs from model initialization:

https://github.com/FLAIROx/jafar/blob/6509ffc0d54e25c177adb8c016a472ae4d376a6d/train_tokenizer.py#L76-L80

instead of the actual training images:

https://github.com/FLAIROx/jafar/blob/6509ffc0d54e25c177adb8c016a472ae4d376a6d/train_tokenizer.py#L147-L151

**Comment by EmptyJackson** [comment]
Good spot, thanks! Fixed there and in the LAM training.
